llm:

  # Video Remixing
  deepseek_api_key: ""  
  deepseek_base_url: ""  

  # Agentic Graph Router
  claude_api_key: ""  
  claude_base_url: ""

  # Video Editing/Overview/Summarization/QA/Text to Commentary Video
  gpt_api_key: ""  
  gpt_base_url: ""  

  # MLLM for caption and fine-grained video understanding
  gemini_api_key: ""  
  gemini_base_url: ""  




#  api_key: ""  # Default/fallback API key
#  base_url: ""  # Default/fallback base URL

#  deepseek_api_key: ""  
#  deepseek_base_url: ""  

  # Agentic Graph Router
#  claude_api_key: ""  
#  claude_base_url: ""

  # Video Editing/Overview/Summarization/QA/Text to Commentary Video
#  gpt_api_key: ""  
#  gpt_base_url: ""  

  # MLLM for caption and fine-grained video understanding
#  gemini_api_key: ""  
#  gemini_base_url: ""  
